spring.application.name=ResQMeal

# Tell Spring where the MySQL database lives
spring.datasource.url=jdbc:mysql://localhost:3306/resqmail_db
spring.datasource.username=root
spring.datasource.password=root

# Show the SQL in the console so you can see it working
spring.jpa.show-sql=true

# Tell Spring to automatically build our tables based on our Entity file
spring.jpa.hibernate.ddl-auto=update