spring.application.name=ResQMeal

# Turn on the H2 Database dashboard
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database connection details
spring.datasource.url=jdbc:h2:mem:fooddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Tell Spring to automatically build our tables based on our Entity file
spring.jpa.hibernate.ddl-auto=update